### ISSUE TITLE
Totally Forgot About This & Waiting for the intro session

### ISSUE THREAD

**Issue by kirtan05** [Vaishakh-SM/php-login-reg#14]

**Comment by Vaishakh-SM** [comment]
Good job making it here!
Try if you can solve it before the intro XD

**Comment by kirtan05** [comment]
Ok bhaiya I will try
Any hints ? Couldn't find text in the image yet

**Comment by Vaishakh-SM** [comment]
Can you write a mail to vaishakhsm@gmail.com stating whatever you have done tll now? Ill reply to that with a hint.

**Comment by kirtan05** [comment]
I have solved it bhaiya 
It was a fun process 
Learnt a lot while solving this
