### ISSUE TITLE
Freshers Definitely count right? 

### ISSUE THREAD

**Issue by Deepanker-Jauhari** [Vaishakh-SM/php-login-reg#3]
And RickRoll seriously? XD

**Comment by Vaishakh-SM** [comment]
Yes freshers definitely count XDD and I'm glad I could rickroll you XDD

**Comment by Deepanker-Jauhari** [comment]
How do I tell you about the Pineapple bhaiya...Any discord link?

**Comment by Vaishakh-SM** [comment]
You can mail me at vaishakhsm@gmail.com or ask some sophomore you know to give my WhatsApp number :P
