### ISSUE TITLE
IITP fresher here 

### ISSUE THREAD

**Issue by parthagarwal04** [Vaishakh-SM/php-login-reg#6]
got the ss 10 minutes back

**Comment by Vaishakh-SM** [comment]
Aww thts unfortunate. I was planning to share the slides sooner but got caught up in some work :(
Good job on making it here! Try to see if you can crack the entire puzzle!

**Comment by parthagarwal04** [comment]
i have done it and texted you the answer as well (on 9th December).

**Comment by Vaishakh-SM** [comment]
Ahh yea. Congrats!
