### ISSUE TITLE
made it here.

### ISSUE THREAD

**Issue by SunnyKrS1ngh** [Vaishakh-SM/php-login-reg#9]
My name is Sunny Kumar Singh, made it here.

**Comment by Vaishakh-SM** [comment]
Hi sunny!
Good job making it till here, try to crack the full puzzle :)

**Comment by SunnyKrS1ngh** [comment]
I have cracked the pineapple puzzle.

**Comment by SunnyKrS1ngh** [comment]
> Hi sunny! Good job making it till here, try to crack the full puzzle :)
